# Generated by Django 3.2.25 on 2026-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Shoes', max_length=100),
            preserve_default=False,
        ),
    ]
